### ISSUE TITLE
[BUG]: Broken staking tests

### ISSUE THREAD

**Issue by NYBACHOK** [rumos-io/gears#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. redelegate_failed_on_invalid_amount

```
---- redelegate_failed_on_invalid_amount stdout ----
thread 'redelegate_failed_on_invalid_amount' panicked at gaia-rs/tests/staking.rs:351:5:
assertion failed: deliver_tx.log.contains("invalid shares amount")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:146:5
   3: staking::redelegate_failed_on_invalid_amount
             at ./tests/staking.rs:351:5
   4: staking::redelegate_failed_on_invalid_amount::{{closure}}
             at ./tests/staking.rs:281:45
   5: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
```

2. query_delegation

```
---- query_delegation stdout ----
thread 'query_delegation' panicked at gaia-rs/tests/staking.rs:452:5:
assertion `left == right` failed
  left: Staking(Delegation(QueryDelegationResponse { delegation_response: Some(DelegationResponse { delegation: Delegation { delegator_address: BaseAddress([129, 58, 194, 42, 97, 73, 22, 85, 226, 120, 106, 224, 209, 39, 214, 153, 11, 251, 251, 222]), validator_address: BaseAddress([129, 58, 194, 42, 97, 73, 22, 85, 226, 120, 106, 224, 209, 39, 214, 153, 11, 251, 251, 222]), shares: Decimal256(110) }, balance: Coin { denom: Denom("uatom"), amount: Uint256(110) } }) }))
 right: Staking(Delegation(QueryDelegationResponse { delegation_response: Some(DelegationResponse { delegation: Delegation { delegator_address: BaseAddress([129, 58, 194, 42, 97, 73, 22, 85, 226, 120, 106, 224, 209, 39, 214, 153, 11, 251, 251, 222]), validator_address: BaseAddress([129, 58, 194, 42, 97, 73, 22, 85, 226, 120, 106, 224, 209, 39, 214, 153, 11, 251, 251, 222]), shares: Decimal256(10) }, balance: Coin { denom: Denom("uatom"), amount: Uint256(10) } }) }))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:409:17
   3: core::panicking::assert_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:364:5
   4: staking::query_delegation
             at ./tests/staking.rs:452:5
   5: staking::query_delegation::{{closure}}
             at ./tests/staking.rs:420:26
   6: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
```

### Gears version

main

**Comment by dmvict** [comment]
Thank you @NYBACHOK for the issue. 

You can look at fix in the PR #145
